nelmio_api_doc:
    documentation:
        info:
            title: Test La Ruche
            description: "Test La Ruche
                        <br>
                        <a href='/api/doc'>Default</a> /
                        <a href='/api/doc/commercial'>Commercial</a>"
            version: 1.0.0
    areas: # to filter documented areas
        default:
            path_patterns:
                - ^/api/doc
        commercial:
            path_patterns:
                - ^/stock